# Generated by Django 2.2.4 on 2019-11-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('costo_alojamiento', models.IntegerField()),
                ('estado', models.CharField(max_length=9)),
                ('id_cliente_fk', models.ForeignKey(db_column='id_cliente_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Cliente', verbose_name='Cliente')),
                ('id_empleado_fk', models.ForeignKey(db_column='id_empleado_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Empleado', verbose_name='Empleado')),
                ('id_habitacion_fk', models.ForeignKey(db_column='id_habitacion_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='estructura.Habitacion', verbose_name='Habitaci&oacute;n')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('total_pago', models.PositiveIntegerField()),
                ('fecha_pago', models.DateTimeField()),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.Reserva', verbose_name='Nro. Reserva')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaServ',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('descuento', models.PositiveIntegerField()),
                ('id_reserva_fk', models.ForeignKey(db_column='id_reserva_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.Reserva', verbose_name='Nro. Reserva')),
                ('id_servicio_fk', models.ForeignKey(db_column='id_servicio_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='estructura.Servicio', verbose_name='Servicio')),
            ],
            options={
                'db_table': 'detalle_venta_serv',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaProd',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('unidades', models.FloatField()),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('obs', models.CharField(max_length=10)),
                ('descuento', models.PositiveIntegerField(blank=True, null=True)),
                ('id_producto_fk', models.ForeignKey(db_column='id_producto_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='estructura.Producto', verbose_name='Producto')),
                ('id_reserva_fk', models.ForeignKey(db_column='id_reserva_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.Reserva', verbose_name='Nro. Reserva')),
            ],
            options={
                'db_table': 'detalle_venta_prod',
            },
        ),
    ]
