# Generated by Django 2.2.5 on 2019-10-11 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHab',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria_hab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categoria_prod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ruc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('costo', models.PositiveIntegerField()),
                ('precio1', models.PositiveIntegerField()),
                ('precio2', models.PositiveIntegerField()),
                ('precio3', models.PositiveIntegerField()),
                ('precio_pack', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.FloatField()),
                ('unid_x_pack', models.FloatField(blank=True, null=True)),
                ('por_pack', models.CharField(blank=True, max_length=7, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('iva', models.PositiveIntegerField()),
                ('lado1', models.FloatField(blank=True, null=True)),
                ('lado2', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estructura.CategoriaProd')),
                ('id_proveedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estructura.Proveedor')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('precio1', models.PositiveIntegerField()),
                ('precio2', models.PositiveIntegerField()),
                ('precio3', models.PositiveIntegerField()),
                ('numero', models.IntegerField(unique=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('estado', models.CharField(max_length=10)),
                ('id_categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estructura.CategoriaHab')),
            ],
            options={
                'db_table': 'habitacion2',
                'managed': True,
            },
        ),
    ]
