# Generated by Django 2.2.4 on 2019-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHab',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=50)),
            ],
            options={
                'db_table': 'categoria_hab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=20)),
            ],
            options={
                'db_table': 'categoria_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(db_column='idHabitacion', primary_key=True, serialize=False)),
                ('precio1', models.PositiveIntegerField(db_column='Precio1')),
                ('precio2', models.PositiveIntegerField(db_column='Precio2')),
                ('precio3', models.PositiveIntegerField(db_column='Precio3')),
                ('numero', models.IntegerField(db_column='Numero', unique=True)),
                ('caracteristicas', models.CharField(blank=True, db_column='Caracteristicas', max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='photos')),
            ],
            options={
                'db_table': 'habitacion2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.CharField(db_column='idProducto', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=50)),
                ('costo', models.PositiveIntegerField(db_column='Costo')),
                ('precio1', models.PositiveIntegerField(db_column='Precio1')),
                ('precio2', models.PositiveIntegerField(db_column='Precio2')),
                ('precio3', models.PositiveIntegerField(db_column='Precio3')),
                ('preciopack', models.PositiveIntegerField(blank=True, db_column='PrecioPack', null=True)),
                ('stock', models.FloatField(db_column='Stock')),
                ('unidxpack', models.FloatField(blank=True, db_column='UnidXpack', null=True)),
                ('porpack', models.CharField(blank=True, db_column='PorPack', max_length=7, null=True)),
                ('foto', models.TextField(blank=True, db_column='Foto', null=True)),
                ('iva', models.PositiveIntegerField(db_column='Iva')),
                ('lado1', models.FloatField(blank=True, db_column='Lado1', null=True)),
                ('lado2', models.FloatField(blank=True, db_column='Lado2', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ruc', models.CharField(db_column='RUC', max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=20, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.CharField(db_column='idServicio', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
    ]
