# Generated by Django 2.2.4 on 2019-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.CharField(db_column='CI', max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ci', models.PositiveIntegerField(db_column='CI', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('apellido', models.CharField(db_column='Apellido', max_length=20)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=30, null=True)),
                ('comision', models.PositiveIntegerField(blank=True, db_column='Comision', null=True)),
                ('estado', models.CharField(db_column='Estado', max_length=8)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('idprivilegio', models.AutoField(db_column='idPrivilegio', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='Rol', max_length=20, unique=True)),
                ('prodconsult', models.TextField(db_column='ProdConsult')),
                ('prodreg', models.TextField(db_column='ProdReg')),
                ('prodactualiz', models.TextField(db_column='ProdActualiz')),
                ('prodeliminar', models.TextField(db_column='ProdEliminar')),
                ('ventasconsult', models.TextField(db_column='VentasConsult')),
                ('ventasreg', models.TextField(db_column='VentasReg')),
                ('comprasconsult', models.TextField(db_column='ComprasConsult')),
                ('comprasreg', models.TextField(db_column='ComprasReg')),
                ('provconsult', models.TextField(db_column='ProvConsult')),
                ('provreg', models.TextField(db_column='ProvReg')),
                ('provactualiz', models.TextField(db_column='ProvActualiz')),
                ('proveliminar', models.TextField(db_column='ProvEliminar')),
                ('empleadmin', models.TextField(db_column='EmpleAdmin')),
                ('usuadmin', models.TextField(db_column='UsuAdmin')),
                ('finanzasadmin', models.TextField(db_column='FinanzasAdmin')),
                ('habadmin', models.TextField(db_column='HabAdmin')),
                ('cuentasadmin', models.TextField(db_column='CuentasAdmin')),
                ('devolautoricli', models.TextField(db_column='DevolAutoriCli')),
                ('devolautoriprov', models.TextField(db_column='DevolAutoriProv')),
            ],
            options={
                'db_table': 'privilegio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=20, unique=True)),
                ('pass_field', models.CharField(db_column='Pass', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
