# Generated by Django 2.2.5 on 2019-10-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id_privilegio', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20, unique=True)),
                ('prod_consult', models.TextField()),
                ('prod_reg', models.TextField()),
                ('prod_actualiz', models.TextField()),
                ('prod_eliminar', models.TextField()),
                ('ventas_consult', models.TextField()),
                ('ventas_reg', models.TextField()),
                ('compras_consult', models.TextField()),
                ('compras_reg', models.TextField()),
                ('prov_consult', models.TextField()),
                ('prov_reg', models.TextField()),
                ('prov_actualiz', models.TextField()),
                ('prov_eliminar', models.TextField()),
                ('emple_admin', models.TextField()),
                ('usu_admin', models.TextField()),
                ('finanzas_admin', models.TextField()),
                ('hab_admin', models.TextField()),
                ('cuentas_admin', models.TextField()),
                ('devol_autori_cli', models.TextField()),
                ('devol_autori_prov', models.TextField()),
            ],
            options={
                'db_table': 'privilegio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('pass_field', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ci', models.PositiveIntegerField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ci', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
                ('comision', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
    ]
