# Generated by Django 2.2.4 on 2019-08-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrados',
            new_name='Registrado',
        ),
    ]
